name: Notificacion de Despliegue

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Ejecutar script de JavaScript
        run: node app.js

      - name: Enviar notificacion a ntfy.sh
        run: |
          curl -H "Title: Hola Mundo - Franklin Báez | 2025-1041" \
               -H "Priority: high" \
               -H "Tags: white_check_mark,rocket" \
               -d "Se subio codigo a main en FranklinJoseBaez/Electiva2. Hola mundo ejecutado con exito." \
               https://ntfy.sh/devops-itla
